### ISSUE TITLE
Does not work with IntelliJ 2017.1

### ISSUE THREAD

**Issue by michael-card** [scalatra/scalatra#643]
I recently upgraded my IntelliJ IDEA IDE to version 2017.1 and after doing so my Scalatra projects would not longer run with the Jetty Runner plug in. When I attempt to run even a trivial "hello world" Scalatra app (the kind produced right out of g8), I get this error:

~~~~
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at org.fusesource.scalate.TemplateEngine.<init>(TemplateEngine.scala:181)
	at org.fusesource.scalate.servlet.ServletTemplateEngine.<init>(ServletTemplateEngine.scala:95)
	at org.scalatra.scalate.ScalateSupport$$anonfun$createTemplateEngine$1$$anon$1.<init>(ScalateSupport.scala:90)
	at org.scalatra.scalate.ScalateSupport$$anonfun$createTemplateEngine$1.apply(ScalateSupport.scala:90)
	at org.scalatra.scalate.ScalateSupport$$anonfun$createTemplateEngine$1.apply(ScalateSupport.scala:90)
	at org.scalatra.scalate.ScalateSupport$$anonfun$scalateTemplateEngine$1.apply(ScalateSupport.scala:37)
	at org.scalatra.scalate.ScalateSupport$$anonfun$scalateTemplateEngine$1.apply(ScalateSupport.scala:36)
	at scala.Option.getOrElse(Option.scala:120)
	at org.scalatra.scalate.ScalateSupport$.scalateTemplateEngine(ScalateSupport.scala:36)
	at org.scalatra.scalate.ScalateSupport$class.createTemplateEngine(ScalateSupport.scala:90)
	at com.dandb.application_services.ApplicationServicesServlet.createTemplateEngine(ApplicationServicesServlet.scala:5)
	at org.scalatra.scalate.ScalateSupport$class.initialize(ScalateSupport.scala:61)
	at com.dandb.application_services.ApplicationServicesServlet.initialize(ApplicationServicesServlet.scala:5)
	at com.dandb.application_services.ApplicationServicesServlet.initialize(ApplicationServicesServlet.scala:5)
	at org.scalatra.ScalatraServlet$class.init(ScalatraServlet.scala:124)
	at com.dandb.application_services.ApplicationServicesServlet.init(ApplicationServicesServlet.scala:5)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:640)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:419)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:349)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:411)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:378)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536)
~~~~

My test project is literally the "hello world" Scalatra project from the First Project part of the help pages, so it is not doing anything sophisticated. I ran an sbt inspect tree clean and compile and I got this, which seemed OK:

~~~~
> inspect tree clean
[info] *:clean = Task[Unit]
[info]   +-*:clean::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | 
[info]   +-*:cleanFiles = List(/Users/cardm/projects/application-services/lib_managed, /Users/cardm/projects/application-services/target)
[info]   | +-{.}/*:managedDirectory = lib_managed
[info]   | +-*:target = target
[info]   |   +-*:baseDirectory = /Users/cardm/projects/application-services
[info]   |     +-*:thisProject = Project(id application-services, base: /Users/cardm/projects/application-services, configurations: List(compile, runtime, test, provide..
[info]   |     
[info]   +-*:cleanKeepFiles = List(/Users/cardm/projects/application-services/target/.history)
[info]   | +-*:history = Some(/Users/cardm/projects/application-services/target/.history)
[info]   |   +-*:target = target
[info]   |     +-*:baseDirectory = /Users/cardm/projects/application-services
[info]   |       +-*:thisProject = Project(id application-services, base: /Users/cardm/projects/application-services, configurations: List(compile, runtime, test, provi..
[info]   |       
[info]   +-*:ivyModule = Task[sbt.IvySbt#sbt.IvySbt$Module]
[info]     +-*:ivySbt = Task[sbt.IvySbt]
[info]     | +-*/*:credentials = Task[scala.collection.Seq[sbt.Credentials]]
[info]     | +-*:ivyConfiguration = Task[sbt.IvyConfiguration]
[info]     | | +-*/*:appConfiguration = xsbt.boot.AppConfiguration@437ed416
[info]     | | +-*:fullResolvers = Task[scala.collection.Seq[sbt.Resolver]]
[info]     | | | +-*:bootResolvers = Task[scala.Option[scala.collection.Seq[sbt.Resolver]]]
[info]     | | | | +-*/*:appConfiguration = xsbt.boot.AppConfiguration@437ed416
[info]     | | | | 
[info]     | | | +-*:externalResolvers = Task[scala.collection.Seq[sbt.Resolver]]
[info]     | | | | +-*:appResolvers = Some(ArrayBuffer(FileRepository(local,FileConfiguration(true,None),Patterns(ivyPatterns=List(${ivy.home}/local/[organisation]/[mod..
[info]     | | | | | +-*/*:appConfiguration = xsbt.boot.AppConfiguration@437ed416
[info]     | | | | | +-*/*:useJcenter = false
[info]     | | | | | 
[info]     | | | | +-*:resolvers = List(URLRepository(typesafe-ivy-releases,Patterns(ivyPatterns=List(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[mo..
[info]     | | | | +-*/*:useJcenter = false
[info]     | | | | 
[info]     | | | +-*:overrideBuildResolvers = false
[info]     | | | | +-*/*:appConfiguration = xsbt.boot.AppConfiguration@437ed416
[info]     | | | | 
[info]     | | | +-*:projectResolver = Task[sbt.Resolver]
[info]     | | | | +-*:projectDescriptors = Task[scala.collection.immutable.Map[org.apache.ivy.core.module.id.ModuleRevisionId, org.apache.ivy.core.module.descriptor.Mo..
[info]     | | | |   +-*/*:buildDependencies = sbt.BuildDependencies@38ac8968
[info]     | | | |   +-*:projectDescriptors::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]     | | | |   | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]     | | | |   | 
[info]     | | | |   +-*/*:settingsData = Task[sbt.Settings[sbt.Scope]]
[info]     | | | |   +-*:thisProjectRef = ProjectRef(file:/Users/cardm/projects/application-services/,application-services)
[info]     | | | |   
[info]     | | | +-*/*:sbtPlugin = false
[info]     | | | +-*/*:sbtResolver = URLRepository(typesafe-ivy-releases,Patterns(ivyPatterns=List(https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[modul..
[info]     | | | 
[info]     | | +-*:ivyConfiguration::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]     | | | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]     | | | 
[info]     | | +-*:ivyPaths = IvyPath(/Users/cardm/projects/application-services, Some(/Users/cardm/.ivy2))
[info]     | | | +-*/*:appConfiguration = xsbt.boot.AppConfiguration@437ed416
[info]     | | | +-*:baseDirectory = /Users/cardm/projects/application-services
[info]     | | |   +-*:thisProject = Project(id application-services, base: /Users/cardm/projects/application-services, configurations: List(compile, runtime, test, pro..
[info]     | | |   
[info]     | | +-*/*:moduleConfigurations = List()
[info]     | | +-*/*:offline = false
[info]     | | +-*:otherResolvers = List(cache:publish-m2-local: /Users/cardm/.m2/repository)
[info]     | | | +-*/*:publishTo = None
[info]     | | | 
[info]     | | +-*:target = target
[info]     | | | +-*:baseDirectory = /Users/cardm/projects/application-services
[info]     | | |   +-*:thisProject = Project(id application-services, base: /Users/cardm/projects/application-services, configurations: List(compile, runtime, test, pro..
[info]     | | |   
[info]     | | +-*/*:checksums = WrappedArray(sha1, md5)
[info]     | | +-*:updateOptions = sbt.UpdateOptions@8bd84cf1
[info]     | |   +-*/*:updateOptions = sbt.UpdateOptions@8bd84cf1
[info]     | |   
[info]     | +-*:ivySbt::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]     |   +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]     |   
[info]     +-*:moduleSettings = Task[sbt.ModuleSettings]
[info]       +-*:allDependencies = Task[scala.collection.Seq[sbt.ModuleID]]
[info]       | +-*:ivyScala = Some(IvyScala(2.12.1,2.12,List(),true,false,true,org.scala-lang))
[info]       | | +-*/*:sbtPlugin = false
[info]       | | +-*/*:scalaHome = None
[info]       | | +-*/*:scalaOrganization = org.scala-lang
[info]       | | +-*:scalaBinaryVersion = 2.12
[info]       | | +-*:scalaVersion = 2.12.1
[info]       | | 
[info]       | +-*:libraryDependencies = List(org.scala-lang:scala-library:2.12.1, org.eclipse.jetty:jetty-runner:9.2.1.v20140609:jetty, org.eclipse.jetty:jetty-runner:..
[info]       | | +-*/*:autoScalaLibrary = true
[info]       | | +-*/*:managedScalaInstance = true
[info]       | | +-*/*:sbtPlugin = false
[info]       | | +-*/*:scalaHome = None
[info]       | | +-*/*:scalaOrganization = org.scala-lang
[info]       | | +-*:scalaVersion = 2.12.1
[info]       | | +-container:containerLibs = List()
[info]       | | +-jetty:containerLibs = List(org.eclipse.jetty:jetty-runner:9.2.1.v20140609)
[info]       | | 
[info]       | +-*/*:managedScalaInstance = true
[info]       | +-*:projectDependencies = Task[scala.collection.Seq[sbt.ModuleID]]
[info]       | | +-*/*:buildDependencies = sbt.BuildDependencies@38ac8968
[info]       | | +-*/*:settingsData = Task[sbt.Settings[sbt.Scope]]
[info]       | | +-*:thisProjectRef = ProjectRef(file:/Users/cardm/projects/application-services/,application-services)
[info]       | | 
[info]       | +-*/*:sbtDependency = org.scala-sbt:sbt:0.13.13
[info]       | +-*/*:sbtPlugin = false
[info]       | +-*/*:scalaHome = None
[info]       | +-*/*:scalaOrganization = org.scala-lang
[info]       | +-*:scalaVersion = 2.12.1
[info]       | 
[info]       +-*/*:conflictManager = ConflictManager(latest-revision,*,*)
[info]       +-*/*:defaultConfiguration = Some(compile)
[info]       +-*/*:dependencyOverrides = Set()
[info]       +-*/*:excludeDependencies = List()
[info]       +-*:ivyConfigurations = List(compile, runtime, test, provided, optional, container, jetty, compile-internal, runtime-internal, test-internal, plugin, sourc..
[info]       | +-*/*:autoCompilerPlugins = true
[info]       | +-*/*:internalConfigurationMap = <function1>
[info]       | +-*/*:managedScalaInstance = true
[info]       | +-*/*:scalaHome = None
[info]       | +-*:thisProject = Project(id application-services, base: /Users/cardm/projects/application-services, configurations: List(compile, runtime, test, provide..
[info]       | 
[info]       +-*:ivyScala = Some(IvyScala(2.12.1,2.12,List(),true,false,true,org.scala-lang))
[info]       | +-*/*:sbtPlugin = false
[info]       | +-*/*:scalaHome = None
[info]       | +-*/*:scalaOrganization = org.scala-lang
[info]       | +-*:scalaBinaryVersion = 2.12
[info]       | +-*:scalaVersion = 2.12.1
[info]       | 
[info]       +-*/*:ivyValidate = false
[info]       +-*/*:ivyXml = 
[info]       +-*:projectId = com.dandb:application-services:0.1.0-SNAPSHOT
[info]       | +-*/*:apiUrl = None
[info]       | +-*:artifacts = List(Artifact(application-services,war,war,None,List(),None,Map()), Artifact(application-services,pom,pom,None,List(pom),None,Map()), Art..
[info]       | | +-*:makePom::artifact = Artifact(application-services,pom,pom,None,List(pom),None,Map())
[info]       | | | +-*:moduleName = application-services
[info]       | | |   +-*:normalizedName = application-services
[info]       | | |     +-*:name = Application Services
[info]       | | |     
[info]       | | +-*:makePom::publishArtifact = true
[info]       | | | +-*/*:publishArtifact = true
[info]       | | | +-*/*:publishMavenStyle = true
[info]       | | | 
[info]       | | +-*:package::artifact = Artifact(application-services,war,war,None,List(),None,Map())
[info]       | | +-compile:packageBin::artifact = Artifact(application-services,jar,jar,None,List(compile),None,Map())
[info]       | | | +-*/*:artifactClassifier = None
[info]       | | | +-compile:configuration = compile
[info]       | | | 
[info]       | | +-*/*:publishArtifact = true
[info]       | | +-compile:packageDoc::artifact = Artifact(application-services,doc,jar,Some(javadoc),List(docs),None,Map())
[info]       | | | +-*/*:packageDoc::artifactClassifier = Some(javadoc)
[info]       | | | +-compile:configuration = compile
[info]       | | | 
[info]       | | +-*/*:publishArtifact = true
[info]       | | +-compile:packageSrc::artifact = Artifact(application-services,src,jar,Some(sources),List(sources),None,Map())
[info]       | | | +-*/*:packageSrc::artifactClassifier = Some(sources)
[info]       | | | +-compile:configuration = compile
[info]       | | | 
[info]       | | +-*/*:publishArtifact = true
[info]       | | +-test:packageBin::artifact = Artifact(application-services,jar,jar,Some(tests),List(test),None,Map())
[info]       | | | +-*/*:artifactClassifier = None
[info]       | | | +-test:configuration = test
[info]       | | | 
[info]       | | +-*/test:publishArtifact = false
[info]       | | +-test:packageDoc::artifact = Artifact(application-services,doc,jar,Some(tests-javadoc),List(docs),None,Map())
[info]       | | | +-*/*:packageDoc::artifactClassifier = Some(javadoc)
[info]       | | | +-test:configuration = test
[info]       | | | 
[info]       | | +-*/test:publishArtifact = false
[info]       | | +-test:packageSrc::artifact = Artifact(application-services,src,jar,Some(tests-sources),List(sources),None,Map())
[info]       | | | +-*/*:packageSrc::artifactClassifier = Some(sources)
[info]       | | | +-test:configuration = test
[info]       | | | 
[info]       | | +-*/test:publishArtifact = false
[info]       | | 
[info]       | +-*/*:autoApiMappings = false
[info]       | +-*:moduleName = application-services
[info]       | | +-*:normalizedName = application-services
[info]       | |   +-*:name = Application Services
[info]       | |   
[info]       | +-*:organization = com.dandb
[info]       | +-*:crossVersion = Binary
[info]       | +-*/*:sbtPlugin = false
[info]       | +-*/*:sbtBinaryVersion = 0.13
[info]       | +-*:scalaBinaryVersion = 2.12
[info]       | +-*:version = 0.1.0-SNAPSHOT
[info]       | 
[info]       +-*:projectInfo = ModuleInfo(Application Services,Application Services,None,None,List(),com.dandb,None,None,List())
[info]         +-*:description = Application Services
[info]         | +-*:name = Application Services
[info]         | 
[info]         +-*/*:developers = List()
[info]         +-*/*:homepage = None
[info]         +-*/*:licenses = List()
[info]         +-*:name = Application Services
[info]         +-*:organizationHomepage = None
[info]         | +-*/*:homepage = None
[info]         | 
[info]         +-*:organizationName = com.dandb
[info]         | +-*:organization = com.dandb
[info]         | 
[info]         +-*/*:scmInfo = None
[info]         +-*/*:startYear = None
[info]         
> inspect tree compile
[info] compile:compile = Task[sbt.inc.Analysis]
[info]   +-compile:incCompileSetup = Task[sbt.Compiler$IncSetup]
[info]   | +-*/*:skip = Task[Boolean]
[info]   | +-compile:compileAnalysisFilename = Task[java.lang.String]
[info]   | | +-*/*:crossPaths = true
[info]   | | +-*:scalaBinaryVersion = 2.12
[info]   | | 
[info]   | +-*/*:compilerCache = Task[xsbti.compile.GlobalsCache]
[info]   | +-*/*:definesClass = Task[scala.Function1[java.io.File, scala.Function1[java.lang.String, Boolean]]]
[info]   | +-compile:dependencyClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]   | | +-compile:dependencyClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | | 
[info]   | | +-compile:externalDependencyClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]   | | | +-compile:externalDependencyClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | | | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | | | 
[info]   | | | +-compile:managedClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]   | | | | +-compile:classpathConfiguration = Task[sbt.Configuration]
[info]   | | | | | +-compile:configuration = compile
[info]   | | | | | +-*/*:internalConfigurationMap = <function1>
[info]   | | | | | +-*:update = Task[sbt.UpdateReport]
[info]   | | | | | 
[info]   | | | | +-*/*:classpathTypes = Set(eclipse-plugin, bundle, scala-jar, hk2-jar, orbit, jar)
[info]   | | | | +-compile:managedClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | | | | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | | | | 
[info]   | | | | +-*:update = Task[sbt.UpdateReport]
[info]   | | | | 
[info]   | | | +-compile:unmanagedClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]   | | |   +-*/*:buildDependencies = sbt.BuildDependencies@38ac8968
[info]   | | |   +-compile:configuration = compile
[info]   | | |   +-*/*:settingsData = Task[sbt.Settings[sbt.Scope]]
[info]   | | |   +-*:thisProjectRef = ProjectRef(file:/Users/cardm/projects/application-services/,application-services)
[info]   | | |   +-compile:unmanagedClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | |     +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | |     
[info]   | | +-compile:internalDependencyClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]   | |   +-*/*:buildDependencies = sbt.BuildDependencies@38ac8968
[info]   | |   +-compile:classpathConfiguration = Task[sbt.Configuration]
[info]   | |   | +-compile:configuration = compile
[info]   | |   | +-*/*:internalConfigurationMap = <function1>
[info]   | |   | +-*:update = Task[sbt.UpdateReport]
[info]   | |   | 
[info]   | |   +-compile:configuration = compile
[info]   | |   +-compile:internalDependencyClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | |   | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | |   | 
[info]   | |   +-*/*:settingsData = Task[sbt.Settings[sbt.Scope]]
[info]   | |   +-*:thisProjectRef = ProjectRef(file:/Users/cardm/projects/application-services/,application-services)
[info]   | |   +-*/*:trackInternalDependencies = TrackAlways
[info]   | |   
[info]   | +-compile:incCompileSetup::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]   | | 
[info]   | +-*:incOptions = Task[sbt.inc.IncOptions]
[info]   | 
[info]   +-compile:manipulateBytecode = Task[sbt.compiler.IC$Result]
[info]     +-compile:compileIncremental = Task[sbt.compiler.IC$Result]
[info]       +-compile:compile::compileInputs = Task[sbt.Compiler$Inputs]
[info]       | +-compile:classDirectory = target/scala-2.12/classes
[info]       | +-*/*:compileOrder = Mixed
[info]       | +-*:compilers = Task[sbt.Compiler$Compilers]
[info]       | +-compile:dependencyClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]       | +-compile:incCompileSetup = Task[sbt.Compiler$IncSetup]
[info]       | +-*/*:javacOptions = Task[scala.collection.Seq[java.lang.String]]
[info]       | +-*/*:maxErrors = 100
[info]       | +-compile:scalacOptions = Task[scala.collection.Seq[java.lang.String]]
[info]       | +-*/*:sourcePositionMappers = Task[scala.collection.Seq[scala.Function1[xsbti.Position, scala.Option[xsbti.Position]]]]
[info]       | +-compile:sources = Task[scala.collection.Seq[java.io.File]]
[info]       | +-compile:compile::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]       |   +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]       |   
[info]       +-compile:compile::compilerReporter = Task[scala.Option[xsbti.Reporter]]
[info]       +-compile:compileIncremental::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]       | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]       | 
[info]       +-compile:readAnalysis = Task[sbt.Compiler$PreviousAnalysis]
[info]         +-compile:incCompileSetup = Task[sbt.Compiler$IncSetup]
[info]           +-*/*:skip = Task[Boolean]
[info]           +-compile:compileAnalysisFilename = Task[java.lang.String]
[info]           | +-*/*:crossPaths = true
[info]           | +-*:scalaBinaryVersion = 2.12
[info]           | 
[info]           +-*/*:compilerCache = Task[xsbti.compile.GlobalsCache]
[info]           +-*/*:definesClass = Task[scala.Function1[java.io.File, scala.Function1[java.lang.String, Boolean]]]
[info]           +-compile:dependencyClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]           | +-compile:dependencyClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | | 
[info]           | +-compile:externalDependencyClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]           | | +-compile:externalDependencyClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | | | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | | | 
[info]           | | +-compile:managedClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]           | | | +-compile:classpathConfiguration = Task[sbt.Configuration]
[info]           | | | | +-compile:configuration = compile
[info]           | | | | +-*/*:internalConfigurationMap = <function1>
[info]           | | | | +-*:update = Task[sbt.UpdateReport]
[info]           | | | | 
[info]           | | | +-*/*:classpathTypes = Set(eclipse-plugin, bundle, scala-jar, hk2-jar, orbit, jar)
[info]           | | | +-compile:managedClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | | | | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | | | | 
[info]           | | | +-*:update = Task[sbt.UpdateReport]
[info]           | | | 
[info]           | | +-compile:unmanagedClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]           | |   +-*/*:buildDependencies = sbt.BuildDependencies@38ac8968
[info]           | |   +-compile:configuration = compile
[info]           | |   +-*/*:settingsData = Task[sbt.Settings[sbt.Scope]]
[info]           | |   +-*:thisProjectRef = ProjectRef(file:/Users/cardm/projects/application-services/,application-services)
[info]           | |   +-compile:unmanagedClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | |     +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | |     
[info]           | +-compile:internalDependencyClasspath = Task[scala.collection.Seq[sbt.Attributed[java.io.File]]]
[info]           |   +-*/*:buildDependencies = sbt.BuildDependencies@38ac8968
[info]           |   +-compile:classpathConfiguration = Task[sbt.Configuration]
[info]           |   | +-compile:configuration = compile
[info]           |   | +-*/*:internalConfigurationMap = <function1>
[info]           |   | +-*:update = Task[sbt.UpdateReport]
[info]           |   | 
[info]           |   +-compile:configuration = compile
[info]           |   +-compile:internalDependencyClasspath::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           |   | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           |   | 
[info]           |   +-*/*:settingsData = Task[sbt.Settings[sbt.Scope]]
[info]           |   +-*:thisProjectRef = ProjectRef(file:/Users/cardm/projects/application-services/,application-services)
[info]           |   +-*/*:trackInternalDependencies = TrackAlways
[info]           |   
[info]           +-compile:incCompileSetup::streams = Task[sbt.std.TaskStreams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | +-*/*:streamsManager = Task[sbt.std.Streams[sbt.Init$ScopedKey[_ <: Any]]]
[info]           | 
[info]           +-*:incOptions = Task[sbt.inc.IncOptions]
[info]        

~~~~

It seems like something about Scalatra is incompatible with IntelliJ 2017.1 as the exact same code runs fine under the exact same Jetty Runner plug-in in IntelliJ 2016.3

**Comment by aadrian** [comment]
@michael-card maybe this is an **IntelliJ problem** with Scala/SBT in general and not Scalatra in particular? 

Jetbrains announced pretty **big refactorings** in 2017.1  https://blog.jetbrains.com/scala/2017/03/23/scala-plugin-for-intellij-idea-2017-1-cleaner-ui-sbt-shell-repl-worksheet-akka-support-and-more/

**Comment by mslinn** [comment]
I have had good experiences with IntelliJ & scala & sbt. Have not tried Scalatra (yet).

**Comment by magnolia-k** [comment]
After that, this issue closes because no similar issues have been reported.
