### ISSUE TITLE
Need help: specs2 2.4.17 -> 3.x

### ISSUE THREAD

**Issue by seratch** [scalatra/scalatra#506]
When upgrading specs2 to 3.x, I got several compilation errors.

```diff
$ git diff
diff --git a/project/build.scala b/project/build.scala
index 405e723..77ec0a8 100644
--- a/project/build.scala
+++ b/project/build.scala
@@ -345,7 +345,7 @@ object ScalatraBuild extends Build {
     lazy val springWeb                =  "org.springframework"     %  "spring-web"                 % "4.1.5.RELEASE"
     lazy val slf4jApi                 =  "org.slf4j"               %  "slf4j-api"                  % "1.7.12"
     lazy val slf4jSimple              =  "org.slf4j"               %  "slf4j-simple"               % "1.7.12"
-    lazy val specs2                   =  "org.specs2"              %% "specs2"                     % specs2Version
+    lazy val specs2                   =  "org.specs2"              %% "specs2-core"                % specs2CoreVersion
     lazy val testJettyServlet         =  "org.eclipse.jetty"       %  "test-jetty-servlet"         % jettyVersion
     lazy val testng                   =  "org.testng"              %  "testng"                     % "6.9.4"
     lazy val metricsScala             =  "nl.grons"                %% "metrics-scala"              % "3.5.1"
@@ -362,8 +362,7 @@ object ScalatraBuild extends Build {
     private val json4sVersion           = "3.3.0.RC2"
     private val scalateVersion          = "1.7.1"
     private val scalatestVersion        = "2.2.5"
-    // TODO: 3.3 has incompatible API changes
-    private val specs2Version           = "2.4.17"
+    private val specs2CoreVersion       = "3.6"
   }
```

```
$ sbt clean test:compile

[error] /Users/seratch/Documents/github/scalatra/specs2/src/main/scala/org/scalatra/test/specs2/BaseScalatraSpec.scala:6: object Fragments is not a member of package org.specs2.specification
[error] import org.specs2.specification.{ Fragments, SpecificationStructure, Step }
[error]        ^
[error] /Users/seratch/Documents/github/scalatra/specs2/src/main/scala/org/scalatra/test/specs2/BaseScalatraSpec.scala:13: not found: type SpecificationStructure
[error] trait BaseScalatraSpec extends SpecificationStructure with FragmentsBuilder with ScalatraTests {
[error]                                ^
[error] /Users/seratch/Documents/github/scalatra/specs2/src/main/scala/org/scalatra/test/specs2/BaseScalatraSpec.scala:5: object FragmentsBuilder is not a member of package org.specs2.mutable
[error] import org.specs2.mutable.FragmentsBuilder
[error]        ^
[error] /Users/seratch/Documents/github/scalatra/specs2/src/main/scala/org/scalatra/test/specs2/BaseScalatraSpec.scala:13: not found: type FragmentsBuilder
[error] trait BaseScalatraSpec extends SpecificationStructure with FragmentsBuilder with ScalatraTests {
[error]                                                            ^
[error] /Users/seratch/Documents/github/scalatra/test/src/test/scala/org/scalatra/test/EmbeddedJettyContainerSpec.scala:6: object Fragments is not a member of package org.specs2.specification
[error] import org.specs2.specification.{ Fragments, Step }
[error]        ^
[error] /Users/seratch/Documents/github/scalatra/test/src/test/scala/org/scalatra/test/EmbeddedJettyContainerSpec.scala:11: not found: type Fragments
[error]   override def map(fs: => Fragments) =
[error]                           ^
[error] /Users/seratch/Documents/github/scalatra/specs2/src/main/scala/org/scalatra/test/specs2/BaseScalatraSpec.scala:14: not found: type Fragments
[error]   override def map(fs: => Fragments) = Step(start()) ^ super.map(fs) ^ Step(stop())
[error]                           ^
[error] /Users/seratch/Documents/github/scalatra/specs2/src/main/scala/org/scalatra/test/specs2/BaseScalatraSpec.scala:14: value ^ is not a member of org.specs2.specification.core.Fragment
[error]   override def map(fs: => Fragments) = Step(start()) ^ super.map(fs) ^ Step(stop())
[error]                                                      ^
[error] /Users/seratch/Documents/github/scalatra/specs2/src/main/scala/org/scalatra/test/specs2/BaseScalatraSpec.scala:14: value map is not a member of org.scalatra.test.ScalatraTests
[error]   override def map(fs: => Fragments) = Step(start()) ^ super.map(fs) ^ Step(stop())
[error]                                                              ^
[error] 7 errors found
[error] /Users/seratch/Documents/github/scalatra/test/src/test/scala/org/scalatra/test/EmbeddedJettyContainerSpec.scala:12: type mismatch;
[error]  found   : org.specs2.specification.core.Fragment
[error]  required: ?{def ^: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method appendToFragment in trait FragmentsDsl of type (f: org.specs2.specification.core.Fragment)EmbeddedJettyContainerSpec.this.appendToFragment
[error]  and method appendSpecStructureToFragment in trait SpecStructureDsl of type (f: org.specs2.specification.core.Fragment)EmbeddedJettyContainerSpec.this.appendSpecStructureToFragment
[error]  are possible conversion functions from org.specs2.specification.core.Fragment to ?{def ^: ?}
[error]     Step(start()) ^ super.map(fs) ^ Step(stop())
[error]         ^
[error] /Users/seratch/Documents/github/scalatra/test/src/test/scala/org/scalatra/test/HttpComponentsClientSpec.scala:7: object Fragments is not a member of package org.specs2.specification
[error] import org.specs2.specification.{ Fragments, Step }
[error]        ^
[error] /Users/seratch/Documents/github/scalatra/test/src/test/scala/org/scalatra/test/HttpComponentsClientSpec.scala:16: not found: type Fragments
[error]   override def map(fs: => Fragments) = Step(start()) ^ super.map(fs) ^ Step(stop())
[error]                           ^
[error] /Users/seratch/Documents/github/scalatra/test/src/test/scala/org/scalatra/test/HttpComponentsClientSpec.scala:16: type mismatch;
[error]  found   : org.specs2.specification.core.Fragment
[error]  required: ?{def ^: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method appendToFragment in trait FragmentsDsl of type (f: org.specs2.specification.core.Fragment)HttpComponentsClientSpec.this.appendToFragment
[error]  and method appendSpecStructureToFragment in trait SpecStructureDsl of type (f: org.specs2.specification.core.Fragment)HttpComponentsClientSpec.this.appendSpecStructureToFragment
[error]  are possible conversion functions from org.specs2.specification.core.Fragment to ?{def ^: ?}
[error]   override def map(fs: => Fragments) = Step(start()) ^ super.map(fs) ^ Step(stop())
[error]                                            ^
[error] 6 errors found
```

To be honest, I'm not a heavy user of specs2. I myself basically use only ScalaTest for test coding. 

If there is someone who hopes to use specs2 3.x for scalatra-specs2 since 2.4.0 final, please help us by working on above errors.

**Comment by etorreborre** [comment]
I'll do that.

**Comment by seratch** [comment]
Thanks a lot!

**Comment by etorreborre** [comment]
It is going to take a bit more time than expected because there is a clash between a `header` variable in one of specs2 traits which is `private[specs2]` but which still conflicts with the `header` method in the `Client` trait from Scalatra.

**Comment by etorreborre** [comment]
BTW I've created a [Scala issue](https://issues.scala-lang.org/browse/SI-9321?jql=text%20~%20%22%5C%22declaring%20an%20override%5C%22%22) for this.
